"""materials product_boms labels

리비전 ID: 56c1462524c9
직전 리비전: 60ca106f8bc7
생성 시각(UTC): 2026-07-30 04:59:55.976076+00:00

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ■ rename 없음 — 신규 테이블 3개뿐이고 **기존 테이블 ALTER가 없다**
    (S1-1 함정 ①은 기존 테이블에 붙는 CHECK만 해당 — 이번엔 비해당).
  ■ CHECK 11건 전부 create_table 안에 포함됐다. 모델과 1:1 대조 완료:
    materials 3(hs6 형식·유형 6값·로트관리→재고관리)
    / product_boms 5(수량>0·원산지 3값·금액↔통화 쌍·단가≥0·통화 대문자)
    / labels 3(국가코드 형식·승인상태 3값·판번>0).
  ■ server_default 3건 감지 확인: product_boms.origin_status='UNKNOWN'(§4.4 미상
    기본값 — GC-B2의 마스터 쪽 전제), labels.approval_status='DRAFT',
    materials/labels의 bool false들.
  ■ 멱등 UNIQUE 3건 전부 unique_active 부분 인덱스(WHERE deleted_at IS NULL).
    최장 이름 50자(uq_labels_sku_id_country_code_label_version_active)로 상한 여유.
    ★ 유일키에 금액 이름(unit_cost)이 들어가지 않는다 — ADR-0018 ㉠(위반 시
    PostgreSQL이 DETAIL로 그 값을 뱉는다). 아키텍처 테스트가 이를 강제한다.
  ■ downgrade가 인덱스·테이블 전부 되돌린다 — kbos_migr 왕복으로 확인.
  ■ GRANT/REVOKE 없음 — 셋 다 MUTABLE(마스터, table_policy 등록).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "56c1462524c9"
down_revision: str | None = "60ca106f8bc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("material_code", sa.String(length=40), nullable=False),
        sa.Column("name_ko", sa.String(length=200), nullable=False),
        sa.Column("material_type", sa.String(length=20), nullable=False),
        sa.Column("hs6", sa.String(length=6), nullable=True),
        sa.Column("default_supplier_name", sa.String(length=100), nullable=True),
        sa.Column(
            "inventory_managed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("lot_managed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("hs6 ~ '^[0-9]{6}$'", name=op.f("ck_materials_hs6_digits")),
        sa.CheckConstraint(
            "material_type IN ('AUX', 'BULK', 'CARTON', 'CONTAINER', 'LABEL', 'RAW_MATERIAL')",
            name=op.f("ck_materials_material_type_valid"),
        ),
        sa.CheckConstraint(
            "lot_managed = false OR inventory_managed = true",
            name=op.f("ck_materials_lot_managed_requires_inventory_managed"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_materials_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_materials_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
    )
    op.create_index(
        "uq_materials_material_code_active",
        "materials",
        ["material_code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "product_boms",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("material_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("quantity_unit", sa.String(length=10), nullable=False),
        sa.Column("unit_cost", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=True),
        sa.Column("origin_status", sa.String(length=10), server_default="UNKNOWN", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "origin_status IN ('DOMESTIC', 'FOREIGN', 'UNKNOWN')",
            name=op.f("ck_product_boms_origin_status_valid"),
        ),
        sa.CheckConstraint(
            "(unit_cost IS NULL AND currency IS NULL) OR (unit_cost IS NOT NULL AND currency IS NOT NULL)",
            name=op.f("ck_product_boms_cost_currency_pair"),
        ),
        sa.CheckConstraint(
            "currency = upper(currency)", name=op.f("ck_product_boms_currency_uppercase")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_product_boms_quantity_positive")),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_product_boms_unit_cost_nonnegative")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_product_boms_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_product_boms_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_boms_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_product_boms_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_boms")),
    )
    op.create_index(
        "uq_product_boms_product_id_material_id_active",
        "product_boms",
        ["product_id", "material_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("sku_id", sa.BigInteger(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("label_version", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("approval_status", sa.String(length=10), server_default="DRAFT", nullable=False),
        sa.Column("cut_in_date", sa.Date(), nullable=True),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column(
            "inci_local_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "origin_mark_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "approval_status IN ('APPROVED', 'DRAFT', 'RETIRED')",
            name=op.f("ck_labels_approval_status_valid"),
        ),
        sa.CheckConstraint(
            "country_code ~ '^[A-Z]{2}$'", name=op.f("ck_labels_country_code_format")
        ),
        sa.CheckConstraint("label_version > 0", name=op.f("ck_labels_label_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_labels_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["skus.id"], name=op.f("fk_labels_sku_id_skus"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_labels_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labels")),
    )
    op.create_index(
        "uq_labels_sku_id_country_code_label_version_active",
        "labels",
        ["sku_id", "country_code", "label_version"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_labels_sku_id_country_code_label_version_active",
        table_name="labels",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("labels")
    op.drop_index(
        "uq_product_boms_product_id_material_id_active",
        table_name="product_boms",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("product_boms")
    op.drop_index(
        "uq_materials_material_code_active",
        table_name="materials",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("materials")
    # ### end Alembic commands ###
