"""set components

리비전 ID: 0f68d6635b0f
직전 리비전: 22531fb72e82
생성 시각(UTC): 2026-07-29 02:31:21.975502+00:00

S1-1 네 번째 마이그레이션 — §4.2의 세트 구성(GC-E1의 "본품 2 + 미니 1").

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ☑ 컬럼 rename이 drop+add로 생성되지 않았는가 → 신규 테이블뿐
  ☑ CHECK 제약·부분 인덱스·server_default·트리거·GRANT는 자동 감지되지 않는다 — 손으로 썼는가
     → 신규 테이블이라 CHECK 2건(quantity_positive·no_self_reference)이 자동
       반영됐다(커밋 4와 같다 — 미감지는 **기존 테이블에 붙는** CHECK일 때다).
       불변 테이블 아님 → revoke_mutations() 대상 아님(MUTABLE_TABLES 등록).
  ☑ 멱등 UNIQUE는 unique_active() 부분 인덱스인가 (§17.4)
     → uq_set_components_set_sku_id_component_sku_id_active
  ☑ downgrade()가 실제로 되돌리는가 → 인덱스·테이블 제거로 완전 복귀
  ☑ 되돌릴 수 없는 변경 없음

■ DB가 못 잠그는 두 규칙 (§4.2 / ADR-0016)

  "set_sku는 kind='SET'" / "구성품은 kind='SINGLE'(중첩 세트 금지)"은 둘 다
  **다른 행**을 봐야 판정되므로 CHECK로 쓸 수 없다. 트리거를 쓰지 않는 이유는
  ORM에서 보이지 않아 마이그레이션·테스트가 어려워지고 규칙이 두 곳으로
  갈라지기 때문이다 — 서비스가 검증하고 테스트가 지킨다. 한 행 안에서 판정되는
  자기 참조만 CHECK(no_self_reference)로 막았다.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0f68d6635b0f"
down_revision: str | None = "22531fb72e82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "set_components",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("set_sku_id", sa.BigInteger(), nullable=False),
        sa.Column("component_sku_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_set_components_quantity_positive")),
        sa.CheckConstraint(
            "set_sku_id <> component_sku_id", name=op.f("ck_set_components_no_self_reference")
        ),
        sa.ForeignKeyConstraint(
            ["component_sku_id"],
            ["skus.id"],
            name=op.f("fk_set_components_component_sku_id_skus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_set_components_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["set_sku_id"],
            ["skus.id"],
            name=op.f("fk_set_components_set_sku_id_skus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_set_components_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_set_components")),
    )
    op.create_index(
        "uq_set_components_set_sku_id_component_sku_id_active",
        "set_components",
        ["set_sku_id", "component_sku_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_set_components_set_sku_id_component_sku_id_active",
        table_name="set_components",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("set_components")
    # ### end Alembic commands ###
