"""requirement template tables

리비전 ID: 3d5723c069d1
직전 리비전: b3ed5c8a5801
생성 시각(UTC): 2026-08-10 00:54:51.492121+00:00

요건 템플릿 4테이블 신설 (§5.1·§4.8·§3 [M2] / WBS S2-1 / s2-1-plan.md §0-1
①·④·조건 1·2 — 조건 2: 완료 보고에 이 DDL 전문 포함 / ADR-0033·0034·0035).

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ■ rename 없음 — 신규 테이블 4개뿐, 기존 테이블 ALTER 없음(함정 ① 비해당).
  ■ CHECK 12건은 전부 신규 테이블이라 create_table 안에 자동 포함됐다 — 모델과
    1:1 대조 완료. 핵심 3건: ★ confirmed_requires_evidence(확정 게이트의 DB
    층 — §5.5 "근거 없는 항목 확정 차단"·GC-C8) ★ no_self_reference(조건 1 —
    순환 참조의 깊이 1은 DB, 깊이 2+는 서비스 검증) ★ estimated_cost_pair
    (금액 규약 ADR-0003 ④ — credit_limit 선례 꼴, 비마스킹 판정 안건 4).
  ■ 멱등 UNIQUE 4건 전부 unique_active 부분 인덱스(§17.4) — 이름 63자 상한
    초과 2건은 수기 축약(uq_template_prerequisites_pair_active·
    uq_item_profile_requirement_templates_profile_template_active — S1-3
    profile_type 선례). FK 이름 63자 초과 3건도 수기 축약(모델에 명시,
    초안이 문자열 그대로 보존 — 이미 최종 이름이라 op.f() 비대상).
  ■ server_default는 믹스인(now()·version=1) + status='DRAFT'(라벨
    approval_status 선례)뿐 — 그 외 도메인 기본값 없음.
  ■ 시드 없음 — T1 시드는 S2-4 몫(조건 12·함정 ⑩), PRESERVED_TABLES 비대상.
    믹스인 전부(Actor 포함) 부착이 그 제약의 원인이며 관찰 원장 등재됐다.
  ■ downgrade는 역순 drop_table 4건으로 완결 — CI 드라이런 왕복 대상.
  ■ GRANT/REVOKE 없음 — 4테이블 전부 MUTABLE(편집 마스터, table_policy 등록).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "3d5723c069d1"
down_revision: str | None = "b3ed5c8a5801"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirement_templates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("applies_to", sa.String(length=10), nullable=False),
        sa.Column("requirement_type", sa.String(length=40), nullable=False),
        sa.Column("validity_months", sa.Integer(), nullable=True),
        sa.Column("renewal_cycle_months", sa.Integer(), nullable=True),
        sa.Column("renewal_lead_days", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_amount", sa.BigInteger(), nullable=True),
        sa.Column("estimated_cost_currency", sa.CHAR(length=3), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("last_verified_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="DRAFT", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "applies_to IN ('COMPANY', 'FACILITY', 'INGREDIENT', 'PRODUCT', 'SKU')",
            name=op.f("ck_requirement_templates_applies_to_valid"),
        ),
        sa.CheckConstraint(
            "requirement_type ~ '^[A-Z][A-Z0-9_]{0,39}$'",
            name=op.f("ck_requirement_templates_requirement_type_format"),
        ),
        sa.CheckConstraint(
            "status <> 'CONFIRMED' OR (source_url IS NOT NULL AND last_verified_on IS NOT NULL)",
            name=op.f("ck_requirement_templates_confirmed_requires_evidence"),
        ),
        sa.CheckConstraint(
            "status IN ('CONFIRMED', 'DRAFT', 'RETIRED')",
            name=op.f("ck_requirement_templates_status_valid"),
        ),
        sa.CheckConstraint(
            "(estimated_cost_amount IS NULL AND estimated_cost_currency IS NULL) OR (estimated_cost_amount IS NOT NULL AND estimated_cost_currency IS NOT NULL)",
            name=op.f("ck_requirement_templates_estimated_cost_pair"),
        ),
        sa.CheckConstraint(
            "estimated_cost_amount >= 0",
            name=op.f("ck_requirement_templates_estimated_cost_amount_nonnegative"),
        ),
        sa.CheckConstraint(
            "estimated_cost_currency = upper(estimated_cost_currency)",
            name=op.f("ck_requirement_templates_estimated_cost_currency_uppercase"),
        ),
        sa.CheckConstraint(
            "renewal_cycle_months > 0",
            name=op.f("ck_requirement_templates_renewal_cycle_months_positive"),
        ),
        sa.CheckConstraint(
            "renewal_lead_days > 0",
            name=op.f("ck_requirement_templates_renewal_lead_days_positive"),
        ),
        sa.CheckConstraint(
            "source_url IS NULL OR length(btrim(source_url)) > 0",
            name=op.f("ck_requirement_templates_source_url_not_blank"),
        ),
        sa.CheckConstraint(
            "validity_months > 0", name=op.f("ck_requirement_templates_validity_months_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_requirement_templates_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_requirement_templates_market_id_markets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_requirement_templates_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_templates")),
    )
    op.create_index(
        "uq_requirement_templates_market_id_name_active",
        "requirement_templates",
        ["market_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "item_profile_requirement_templates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("item_profile_id", sa.BigInteger(), nullable=False),
        sa.Column("requirement_template_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_item_profile_requirement_templates_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["item_profile_id"],
            ["item_profiles.id"],
            name="fk_item_profile_requirement_templates_profile",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_template_id"],
            ["requirement_templates.id"],
            name="fk_item_profile_requirement_templates_template",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_item_profile_requirement_templates_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_profile_requirement_templates")),
    )
    op.create_index(
        "uq_item_profile_requirement_templates_profile_template_active",
        "item_profile_requirement_templates",
        ["item_profile_id", "requirement_template_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "template_checklist",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("template_id", sa.BigInteger(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=200), nullable=False),
        sa.Column("document_type_id", sa.BigInteger(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("seq > 0", name=op.f("ck_template_checklist_seq_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_template_checklist_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_template_checklist_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["requirement_templates.id"],
            name=op.f("fk_template_checklist_template_id_requirement_templates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_template_checklist_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_checklist")),
    )
    op.create_index(
        "uq_template_checklist_template_id_seq_active",
        "template_checklist",
        ["template_id", "seq"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "template_prerequisites",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("template_id", sa.BigInteger(), nullable=False),
        sa.Column("prerequisite_template_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "template_id <> prerequisite_template_id",
            name=op.f("ck_template_prerequisites_no_self_reference"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_template_prerequisites_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_template_id"],
            ["requirement_templates.id"],
            name="fk_template_prerequisites_prerequisite_requirement_templates",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["requirement_templates.id"],
            name=op.f("fk_template_prerequisites_template_id_requirement_templates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_template_prerequisites_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_prerequisites")),
    )
    op.create_index(
        "uq_template_prerequisites_pair_active",
        "template_prerequisites",
        ["template_id", "prerequisite_template_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_template_prerequisites_pair_active",
        table_name="template_prerequisites",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("template_prerequisites")
    op.drop_index(
        "uq_template_checklist_template_id_seq_active",
        table_name="template_checklist",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("template_checklist")
    op.drop_index(
        "uq_item_profile_requirement_templates_profile_template_active",
        table_name="item_profile_requirement_templates",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("item_profile_requirement_templates")
    op.drop_index(
        "uq_requirement_templates_market_id_name_active",
        table_name="requirement_templates",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("requirement_templates")
    # ### end Alembic commands ###
