"""partners item codes signatories

리비전 ID: 81fe6e5c01cc
직전 리비전: 56c1462524c9
생성 시각(UTC): 2026-08-05 07:53:49.400811+00:00

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ■ rename 없음 — 신규 테이블 4개뿐이고 **기존 테이블 ALTER가 없다**
    (S1-1 함정 ①은 기존 테이블에 붙는 CHECK만 해당 — 이번엔 비해당.
    제조사·공급사 FK 승격의 기존 테이블 ALTER는 다음 마이그레이션이다).
  ■ CHECK 4건 전부 create_table 안에 포함됐다. 모델과 1:1 대조 완료:
    partners 3(여신 금액↔통화 쌍·금액≥0·통화 대문자) / partner_type_links 1
    (유형 10값 — §4.6 열거와 1:1, ADR-0026).
  ■ 멱등 UNIQUE 3건 전부 unique_active 부분 인덱스(WHERE deleted_at IS NULL).
    최장 이름 56자(uq_customer_item_codes_partner_id_buyer_item_code_active)로
    상한(63자) 안. ★ 유일키에 금액 이름 없음(credit_limit_amount는 키 밖 —
    ADR-0018 ㉠, 아키텍처 테스트가 강제).
  ■ signatories는 CHECK·유니크 없음이 **의도**다 — 최소 헤더([M1] 보강(S1-3)
    ④), 동명이인 허용, 더블클릭은 idempotency key가 흡수.
  ■ server_default는 믹스인 3종(now()·version=1)뿐 — 도메인 기본값 없음 확인.
  ■ downgrade가 인덱스·테이블 전부 되돌린다 — CI 드라이런 왕복 대상.
  ■ GRANT/REVOKE 없음 — 넷 다 MUTABLE(마스터, table_policy 등록).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '81fe6e5c01cc'
down_revision: str | None = '56c1462524c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('partner_code', sa.String(length=40), nullable=False),
    sa.Column('name_ko', sa.String(length=200), nullable=False),
    sa.Column('credit_limit_amount', sa.BigInteger(), nullable=True),
    sa.Column('credit_limit_currency', sa.CHAR(length=3), nullable=True),
    sa.Column('dg_capable', sa.Boolean(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('(credit_limit_amount IS NULL AND credit_limit_currency IS NULL) OR (credit_limit_amount IS NOT NULL AND credit_limit_currency IS NOT NULL)', name=op.f('ck_partners_credit_limit_pair')),
    sa.CheckConstraint('credit_limit_amount >= 0', name=op.f('ck_partners_credit_limit_amount_nonnegative')),
    sa.CheckConstraint('credit_limit_currency = upper(credit_limit_currency)', name=op.f('ck_partners_credit_limit_currency_uppercase')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_partners_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_partners_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners'))
    )
    op.create_index('uq_partners_partner_code_active', 'partners', ['partner_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('signatories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_signatories_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_signatories_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signatories'))
    )
    op.create_table('partner_type_links',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('type_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("type_code IN ('BUYER', 'CERT_AGENCY', 'CUSTOMS_BROKER', 'DOMESTIC_RP', 'FORWARDER', 'IOR', 'OEM', 'RP', 'SUPPLIER', 'THREE_PL')", name=op.f('ck_partner_type_links_type_code_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_partner_type_links_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_type_links_partner_id_partners'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_partner_type_links_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_type_links'))
    )
    op.create_index('uq_partner_type_links_partner_id_type_code_active', 'partner_type_links', ['partner_id', 'type_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('customer_item_codes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_item_code', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customer_item_codes_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_customer_item_codes_partner_id_partners'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_customer_item_codes_sku_id_skus'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_customer_item_codes_updated_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_item_codes'))
    )
    op.create_index('uq_customer_item_codes_partner_id_buyer_item_code_active', 'customer_item_codes', ['partner_id', 'buyer_item_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_customer_item_codes_partner_id_buyer_item_code_active', table_name='customer_item_codes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('customer_item_codes')
    op.drop_index('uq_partner_type_links_partner_id_type_code_active', table_name='partner_type_links', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('partner_type_links')
    op.drop_table('signatories')
    op.drop_index('uq_partners_partner_code_active', table_name='partners', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('partners')
    # ### end Alembic commands ###
