"""skus minimal for vertical slice

리비전 ID: 65f7c2c5b6fa
직전 리비전: 238dad88bdf5
생성 시각(UTC): 2026-07-27 09:44:51.937494+00:00

S0-2 세 번째 마이그레이션 — §19 Phase 0의 "SKU 등록→목록→CSV 끝-끝 관통"용
**최소 컬럼**. 바코드·중량·박스입수·shelf_life·제조사·DG 속성 전체는 §4.1대로
S1-1이 추가한다. 지금 다 만들면 쓰이지 않는 컬럼이 먼저 굳는다.

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ☑ 컬럼 rename이 drop+add로 생성되지 않았는가 → 신규 테이블뿐
  ☑ CHECK 제약·부분 인덱스·server_default·트리거·GRANT는 자동 감지되지 않는다 — 손으로 썼는가
     → status CHECK와 품번 부분 유니크는 모델 __table_args__에서 나와 반영됨.
       불변 테이블 아님 → revoke_mutations() 대상 아님(MUTABLE_TABLES 등록).
  ☑ 멱등 UNIQUE는 unique_active() 부분 인덱스인가 (§17.4)
     → uq_skus_sku_code_active. 단종 SKU를 soft delete해도 같은 품번의
       재등록이 영구 차단되지 않는다.
  ☑ downgrade()가 실제로 되돌리는가 → 시드 없음, drop_table로 완전 복귀
  ☑ 되돌릴 수 없는 변경 없음
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "65f7c2c5b6fa"
down_revision: str | None = "238dad88bdf5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skus",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("sku_code", sa.String(length=40), nullable=False),
        sa.Column("name_ko", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'DISCONTINUED')", name=op.f("ck_skus_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_skus_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_skus_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skus")),
    )
    op.create_index(
        "uq_skus_sku_code_active",
        "skus",
        ["sku_code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_skus_sku_code_active", table_name="skus", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_table("skus")
    # ### end Alembic commands ###
