"""markets master

리비전 ID: 5df0df5da551
직전 리비전: a7c3e9f2d4b8
생성 시각(UTC): 2026-08-07 07:25:24.639720+00:00

시장 마스터 신설 (§5.1·§3 [M2] / WBS S2-1 / s2-1-plan.md §0-1 ①·② — 조건 2:
완료 보고에 이 DDL 전문 포함).

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ■ rename 없음 — 신규 테이블 1개뿐, 기존 테이블 ALTER 없음(함정 ① 비해당.
    country_code FK 승격의 기존 테이블 ALTER는 다음 마이그레이션이다).
  ■ CHECK 1건(code 형식)은 신규 테이블이라 create_table 안에 자동 포함됐다 —
    모델과 1:1 대조 완료.
  ■ ★ code는 **전역 UNIQUE**(uq_markets_code)이고 unique_active 부분 인덱스가
    **아니다** — 의도다(S2-1 판정 조건 3). country_code가 값으로 참조하는
    FK 대상이라 부분 유니크로는 FK가 성립하지 않고, 같은 코드의 신·구 행
    공존은 참조 의미를 무너뜨린다. §17.4의 부분 유니크 규율은 멱등 키 대상
    (모델 독스트링·ADR 참조).
  ■ server_default는 믹스인(now()·version=1)뿐 — 도메인 기본값 없음.
  ■ 시드 없음 — T1 시드는 S2-4 몫(계획서 §2), PRESERVED_TABLES 비대상.
  ■ downgrade는 drop_table 하나로 완결 — CI 드라이런 왕복 대상.
  ■ GRANT/REVOKE 없음 — MUTABLE(마스터, table_policy 등록).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "5df0df5da551"
down_revision: str | None = "a7c3e9f2d4b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "markets",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("code ~ '^[A-Z]{2}$'", name=op.f("ck_markets_code_format")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_markets_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_markets_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_markets")),
        sa.UniqueConstraint("code", name=op.f("uq_markets_code")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("markets")
    # ### end Alembic commands ###
