"""certification instance tables

리비전 ID: 3e93b9fc667d
직전 리비전: 3d5723c069d1
생성 시각(UTC): 2026-08-11 06:43:50.963056+00:00

인증 인스턴스 3테이블 신설 (§5.1·§5.2·§3 [M2] / WBS S2-2 / s2-2-plan.md §0-1
안건 ①·③·④·조건 B — DDL 전문은 PR-1 완료 보고 포함 / ADR-0037~0040 예정).

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ■ rename 없음 — 신규 테이블 3개뿐, 기존 테이블 ALTER 없음(함정 ① 비해당.
    documents 소유 CHECK 확장은 PR-2 몫이라 이 리비전에 없다).
  ■ CHECK 15건 전부 신규 테이블이라 create_table 안에 자동 포함 — 모델과 1:1
    대조 완료. 핵심 4건: ★ company_target_null(COMPANY=자사 단일·target_id
    NULL 양방향 — 안건 ②) ★ period_order(§17.5 기간 순서) ★ reason_required
    (조건 B — §5.2 "반려·만료·중단 사유 필수"의 기계화, 만료 포함 3종)
    ★ no_self_transition(machine.py에 자기 쌍이 없다는 사실의 DB 층).
  ■ 유니크 3건: 활성 한정 2건은 술어에 종결 2태 제외가 붙어 unique_active()
    범위 밖 — 수기 Index(안건 ① 술어 전문: deleted_at IS NULL AND status
    NOT IN ('REJECTED','SUSPENDED')). COMPANY 전용 분리는 PG가 유니크에서
    NULL을 구별 취급하기 때문. 태스크 (certification_id, seq)는 unique_active.
  ■ server_default는 믹스인(now()·version=1) + status='NOT_STARTED' +
    done=false뿐 — 그 외 도메인 기본값 없음.
  ■ 시드 없음 — PRESERVED_TABLES 비대상(함정 ⑩ 비적용).
  ■ downgrade는 역순 drop_table 3건으로 완결(FK 역순: tasks→log→본체) —
    CI 드라이런 왕복 대상. REVOKE는 테이블과 함께 소멸한다.
  ■ GRANT/REVOKE: certification_status_log는 불변 이력(판정 안건 ④ —
    §17.5 확장·ADR-0040)이라 revoke_mutations() 수기 호출 — autogenerate
    불감지 영역이다. 본체·태스크 2테이블은 MUTABLE(table_policy 등록).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.core.db.table_policy import revoke_mutations


revision: str = "3e93b9fc667d"
down_revision: str | None = "3d5723c069d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certifications",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("template_id", sa.BigInteger(), nullable=False),
        sa.Column("target_type", sa.String(length=10), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=13), server_default="NOT_STARTED", nullable=False),
        sa.Column("template_name", sa.String(length=200), nullable=False),
        sa.Column("requirement_type", sa.String(length=40), nullable=False),
        sa.Column("validity_months", sa.Integer(), nullable=True),
        sa.Column("renewal_cycle_months", sa.Integer(), nullable=True),
        sa.Column("renewal_lead_days", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("last_verified_on", sa.Date(), nullable=True),
        sa.Column("cert_number", sa.String(length=100), nullable=True),
        sa.Column("applied_on", sa.Date(), nullable=True),
        sa.Column("approved_on", sa.Date(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("assignee_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "(target_type = 'COMPANY') = (target_id IS NULL)",
            name=op.f("ck_certifications_company_target_null"),
        ),
        sa.CheckConstraint(
            "status IN ('APPROVED', 'EXPIRED', 'EXPIRING', 'IN_REVIEW', 'NOT_STARTED', 'PREPARING', 'REJECTED', 'RENEWING', 'SUBMITTED', 'SUPPLEMENTING', 'SUSPENDED')",
            name=op.f("ck_certifications_status_valid"),
        ),
        sa.CheckConstraint(
            "target_type IN ('COMPANY', 'FACILITY', 'INGREDIENT', 'PRODUCT', 'SKU')",
            name=op.f("ck_certifications_target_type_valid"),
        ),
        sa.CheckConstraint(
            "cert_number IS NULL OR length(btrim(cert_number)) > 0",
            name=op.f("ck_certifications_cert_number_not_blank"),
        ),
        sa.CheckConstraint(
            "renewal_cycle_months > 0", name=op.f("ck_certifications_renewal_cycle_months_positive")
        ),
        sa.CheckConstraint(
            "renewal_lead_days > 0", name=op.f("ck_certifications_renewal_lead_days_positive")
        ),
        sa.CheckConstraint(
            "source_url IS NULL OR length(btrim(source_url)) > 0",
            name=op.f("ck_certifications_source_url_not_blank"),
        ),
        sa.CheckConstraint(
            "valid_from IS NULL OR expires_on IS NULL OR valid_from <= expires_on",
            name=op.f("ck_certifications_period_order"),
        ),
        sa.CheckConstraint(
            "validity_months > 0", name=op.f("ck_certifications_validity_months_positive")
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_certifications_assignee_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_certifications_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["requirement_templates.id"],
            name=op.f("fk_certifications_template_id_requirement_templates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_certifications_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certifications")),
    )
    op.create_index(
        "uq_certifications_company_open",
        "certifications",
        ["template_id"],
        unique=True,
        postgresql_where=sa.text(
            "target_type = 'COMPANY' AND deleted_at IS NULL AND status NOT IN ('REJECTED', 'SUSPENDED')"
        ),
    )
    op.create_index(
        "uq_certifications_template_target_open",
        "certifications",
        ["template_id", "target_type", "target_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status NOT IN ('REJECTED', 'SUSPENDED')"),
    )
    op.create_table(
        "certification_status_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("certification_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("from_status", sa.String(length=13), nullable=False),
        sa.Column("to_status", sa.String(length=13), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_on_snapshot", sa.Date(), nullable=True),
        sa.Column("cert_number_snapshot", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "from_status IN ('APPROVED', 'EXPIRED', 'EXPIRING', 'IN_REVIEW', 'NOT_STARTED', 'PREPARING', 'REJECTED', 'RENEWING', 'SUBMITTED', 'SUPPLEMENTING', 'SUSPENDED')",
            name=op.f("ck_certification_status_log_from_status_valid"),
        ),
        sa.CheckConstraint(
            "to_status IN ('APPROVED', 'EXPIRED', 'EXPIRING', 'IN_REVIEW', 'NOT_STARTED', 'PREPARING', 'REJECTED', 'RENEWING', 'SUBMITTED', 'SUPPLEMENTING', 'SUSPENDED')",
            name=op.f("ck_certification_status_log_to_status_valid"),
        ),
        sa.CheckConstraint(
            "to_status NOT IN ('EXPIRED', 'REJECTED', 'SUSPENDED') OR reason IS NOT NULL",
            name=op.f("ck_certification_status_log_reason_required"),
        ),
        sa.CheckConstraint(
            "from_status <> to_status", name=op.f("ck_certification_status_log_no_self_transition")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_certification_status_log_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["certification_id"],
            ["certifications.id"],
            name=op.f("fk_certification_status_log_certification_id_certifications"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certification_status_log")),
    )
    op.create_index(
        "ix_certification_status_log_certification_id",
        "certification_status_log",
        ["certification_id"],
        unique=False,
    )
    op.create_index(
        "ix_certification_status_log_occurred_at",
        "certification_status_log",
        ["occurred_at"],
        unique=False,
    )
    op.create_table(
        "certification_tasks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("certification_id", sa.BigInteger(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=200), nullable=False),
        sa.Column("document_type_id", sa.BigInteger(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("done", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "(done AND done_at IS NOT NULL) OR ((NOT done) AND done_at IS NULL)",
            name=op.f("ck_certification_tasks_done_pair"),
        ),
        sa.CheckConstraint("seq > 0", name=op.f("ck_certification_tasks_seq_positive")),
        sa.ForeignKeyConstraint(
            ["certification_id"],
            ["certifications.id"],
            name=op.f("fk_certification_tasks_certification_id_certifications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_certification_tasks_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_certification_tasks_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_types.id"],
            name=op.f("fk_certification_tasks_document_type_id_document_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_certification_tasks_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certification_tasks")),
    )
    op.create_index(
        "uq_certification_tasks_certification_id_seq_active",
        "certification_tasks",
        ["certification_id", "seq"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # 불변 이력 — 앱 계정의 UPDATE/DELETE를 DB가 거부한다 (판정 안건 ④ —
    # §17.5 확장. GRANT/REVOKE는 autogenerate 불감지라 수기 호출).
    revoke_mutations(op, "certification_status_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_certification_tasks_certification_id_seq_active",
        table_name="certification_tasks",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("certification_tasks")
    op.drop_index("ix_certification_status_log_occurred_at", table_name="certification_status_log")
    op.drop_index(
        "ix_certification_status_log_certification_id", table_name="certification_status_log"
    )
    op.drop_table("certification_status_log")
    op.drop_index(
        "uq_certifications_template_target_open",
        table_name="certifications",
        postgresql_where=sa.text("deleted_at IS NULL AND status NOT IN ('REJECTED', 'SUSPENDED')"),
    )
    op.drop_index(
        "uq_certifications_company_open",
        table_name="certifications",
        postgresql_where=sa.text(
            "target_type = 'COMPANY' AND deleted_at IS NULL AND status NOT IN ('REJECTED', 'SUSPENDED')"
        ),
    )
    op.drop_table("certifications")
    # ### end Alembic commands ###
