"""item profiles header and links

리비전 ID: 306c631abb8f
직전 리비전: 1e916401c142
생성 시각(UTC): 2026-07-29 05:17:57.735106+00:00

S1-1 여섯 번째 마이그레이션 — §4.8의 품목군 프로파일(ADR-0021).

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ☑ 컬럼 rename이 drop+add로 생성되지 않았는가 → 신규 테이블 1개 + 신규 컬럼 2개
  ☑ CHECK 제약·부분 인덱스·server_default·트리거·GRANT는 자동 감지되지 않는다 — 손으로 썼는가
     → 이 마이그레이션에는 CHECK가 없다. 신규 컬럼 두 개는 nullable FK뿐이라
       기존 행 백필도 필요 없다(분류가 없어도 제품·SKU는 존재한다).
       불변 테이블 아님 → MUTABLE_TABLES 등록.
  ☑ 멱등 UNIQUE는 unique_active() 부분 인덱스인가 (§17.4)
     → uq_item_profiles_code_active
  ☑ downgrade()가 실제로 되돌리는가 → FK·컬럼·인덱스·테이블 역순 제거
  ☑ 되돌릴 수 없는 변경 없음

■ 헤더만 만드는 것이 설계다 (ADR-0021)

  §4.8의 "기본 요건 세트·서류 세트·마일스톤 세트"는 대상 테이블이 전부 후속
  세션이다(요건 S2-1 / 서류 S1-3 / 마일스톤 S3-2). 지금 연결 테이블을 만들면
  참조할 대상이 없어 FK 없는 문자열 코드로 채우게 되고, 그 코드는 대상 테이블이
  생겨도 FK로 바뀌지 않는다. **연결은 각 대상이 생기는 세션이 붙인다.**

■ FK를 제품과 SKU 양쪽에 다는 이유

  요건(인증)은 처방 단위지만 서류·마일스톤 세트는 SKU·선적 단위다(§4.8·§7.5).
  한쪽에만 달면 다른 축이 표현되지 않는다.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "306c631abb8f"
down_revision: str | None = "1e916401c142"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_profiles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_item_profiles_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_item_profiles_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_profiles")),
    )
    op.create_index(
        "uq_item_profiles_code_active",
        "item_profiles",
        ["code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.add_column("products", sa.Column("item_profile_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_products_item_profile_id_item_profiles"),
        "products",
        "item_profiles",
        ["item_profile_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column("skus", sa.Column("item_profile_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_skus_item_profile_id_item_profiles"),
        "skus",
        "item_profiles",
        ["item_profile_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_skus_item_profile_id_item_profiles"), "skus", type_="foreignkey")
    op.drop_column("skus", "item_profile_id")
    op.drop_constraint(
        op.f("fk_products_item_profile_id_item_profiles"), "products", type_="foreignkey"
    )
    op.drop_column("products", "item_profile_id")
    op.drop_index(
        "uq_item_profiles_code_active",
        table_name="item_profiles",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("item_profiles")
    # ### end Alembic commands ###
