"""sku logistics and dangerous goods attributes

리비전 ID: 7c4162d3ceb1
직전 리비전: c2f216777de3
생성 시각(UTC): 2026-07-29 01:31:08.144075+00:00

S1-1 두 번째 마이그레이션 — §4.1의 SKU 물류·DG 속성 전체.

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ☑ 컬럼 rename이 drop+add로 생성되지 않았는가 → 신규 컬럼 14개뿐
  ☑ CHECK 제약·부분 인덱스·server_default·트리거·GRANT는 자동 감지되지 않는다 — 손으로 썼는가
     → **CHECK 6건 전부 미감지. 손으로 추가**했다(컬럼 14개는 감지, 제약은 0건 —
       커밋 2에서 확인된 것과 같은 함정이다). server_default(false 3건)는 감지됐다.
  ☑ 멱등 UNIQUE 해당 없음 (신규 키 없음)
  ☑ downgrade()가 실제로 되돌리는가 → CHECK 먼저 제거 후 컬럼 제거
  ☑ 되돌릴 수 없는 변경 없음

■ CHECK 6건이 무엇을 막나 (ADR-0016 정정 / ADR-0003 ⑧)

  ① set_has_no_dg — 세트는 DG 속성을 **하나도** 갖지 않는다. 세트의 DG를 자체
     입력할지 구성품 롤업으로 계산할지는 §7.7 DG 게이트(P4)의 미결 사항이라,
     그때까지 입력을 열어 두면 구성품과 어긋난 값이 쌓이고 P4에서 전건 재입력
     대상이 된다.
  ② dg_classification_only_when_dangerous — 비DG 행에 UN번호·Class·포장등급·LQ가
     남아 있으면 안 된다. **인화점·알코올함량·에어로졸·MSDS는 여기 없다** —
     그건 "왜 DG가 아닌지"의 근거값이라 비DG 행에도 있어야 한다.
  ③~⑥ 상식 범위 — 중량>0, 박스입수>0, 사용기한>0, 알코올함량 0~100.
     NULL은 통과한다(SQL CHECK는 식이 FALSE일 때만 거부한다) — "값이 있으면
     지켜야 한다"가 정확히 이 의미다.

  ★ 여기서 **막지 않는 것**도 의도다: dg_flag=true 방향의 완결성(UN번호 필수 등)과
    교차 정합(에어로졸=true인데 dg_flag=false)은 §7.7 DG 게이트(P4)가 맡는다.
    등록 시점에 DG 정보가 다 모여 있지 않은 것이 실무의 정상 상태이고, 차단해야
    할 지점은 등록이 아니라 선적이다. 근거 데이터(IATA DGR·IMDG)가 서기 전에
    DB로 잠그면 근거 없는 차단이 된다.

■ 기존 행

  전부 nullable이거나 server_default가 있어 백필이 필요 없다. 기존 SKU는
  dg_flag=false·is_aerosol=false·is_limited_quantity=false로 채워지고, 그 상태는
  ②를 그대로 만족한다(분류값이 전부 NULL이므로).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "7c4162d3ceb1"
down_revision: str | None = "c2f216777de3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: 세트가 가질 수 없는 DG 속성 전체.
_SET_HAS_NO_DG = (
    "kind <> 'SET' OR ("
    " dg_flag = false AND un_number IS NULL AND dg_class IS NULL"
    " AND packing_group IS NULL AND flash_point_c IS NULL"
    " AND alcohol_content_pct IS NULL AND is_aerosol = false"
    " AND is_limited_quantity = false AND msds_url IS NULL)"
)

#: DG 분류가 있어야만 의미가 생기는 값들.
_DG_CLASSIFICATION_ONLY_WHEN_DANGEROUS = (
    "dg_flag = true OR ("
    " un_number IS NULL AND dg_class IS NULL AND packing_group IS NULL"
    " AND is_limited_quantity = false)"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skus", sa.Column("barcode", sa.String(length=20), nullable=True))
    op.add_column(
        "skus", sa.Column("unit_weight_g", sa.Numeric(precision=10, scale=3), nullable=True)
    )
    op.add_column("skus", sa.Column("box_qty", sa.Integer(), nullable=True))
    op.add_column("skus", sa.Column("shelf_life_months", sa.Integer(), nullable=True))
    op.add_column("skus", sa.Column("manufacturer_name", sa.String(length=100), nullable=True))
    op.add_column(
        "skus", sa.Column("dg_flag", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column("skus", sa.Column("un_number", sa.String(length=10), nullable=True))
    op.add_column("skus", sa.Column("dg_class", sa.String(length=10), nullable=True))
    op.add_column("skus", sa.Column("packing_group", sa.String(length=3), nullable=True))
    op.add_column(
        "skus", sa.Column("flash_point_c", sa.Numeric(precision=5, scale=1), nullable=True)
    )
    op.add_column(
        "skus", sa.Column("alcohol_content_pct", sa.Numeric(precision=5, scale=2), nullable=True)
    )
    op.add_column(
        "skus",
        sa.Column("is_aerosol", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "skus",
        sa.Column(
            "is_limited_quantity", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column("skus", sa.Column("msds_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

    # ↓ 손으로 추가한 부분 — autogenerate가 CHECK를 감지하지 못한다.
    op.create_check_constraint(op.f("ck_skus_set_has_no_dg"), "skus", _SET_HAS_NO_DG)
    op.create_check_constraint(
        op.f("ck_skus_dg_classification_only_when_dangerous"),
        "skus",
        _DG_CLASSIFICATION_ONLY_WHEN_DANGEROUS,
    )
    op.create_check_constraint(op.f("ck_skus_unit_weight_g_positive"), "skus", "unit_weight_g > 0")
    op.create_check_constraint(op.f("ck_skus_box_qty_positive"), "skus", "box_qty > 0")
    op.create_check_constraint(
        op.f("ck_skus_shelf_life_months_positive"), "skus", "shelf_life_months > 0"
    )
    op.create_check_constraint(
        op.f("ck_skus_alcohol_content_pct_range"), "skus", "alcohol_content_pct BETWEEN 0 AND 100"
    )


def downgrade() -> None:
    for name in (
        "ck_skus_alcohol_content_pct_range",
        "ck_skus_shelf_life_months_positive",
        "ck_skus_box_qty_positive",
        "ck_skus_unit_weight_g_positive",
        "ck_skus_dg_classification_only_when_dangerous",
        "ck_skus_set_has_no_dg",
    ):
        op.drop_constraint(op.f(name), "skus", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skus", "msds_url")
    op.drop_column("skus", "is_limited_quantity")
    op.drop_column("skus", "is_aerosol")
    op.drop_column("skus", "alcohol_content_pct")
    op.drop_column("skus", "flash_point_c")
    op.drop_column("skus", "packing_group")
    op.drop_column("skus", "dg_class")
    op.drop_column("skus", "un_number")
    op.drop_column("skus", "dg_flag")
    op.drop_column("skus", "manufacturer_name")
    op.drop_column("skus", "shelf_life_months")
    op.drop_column("skus", "box_qty")
    op.drop_column("skus", "unit_weight_g")
    op.drop_column("skus", "barcode")
    # ### end Alembic commands ###
