"""sku price history

리비전 ID: 1e916401c142
직전 리비전: 0f68d6635b0f
생성 시각(UTC): 2026-07-29 04:24:52.300265+00:00

S1-1 다섯 번째 마이그레이션 — §4.1의 단가 이력(ADR-0017).

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ☑ 컬럼 rename이 drop+add로 생성되지 않았는가 → 신규 테이블뿐
  ☑ CHECK 제약·부분 인덱스·server_default·트리거·GRANT는 자동 감지되지 않는다 — 손으로 썼는가
     → 신규 테이블이라 CHECK 3건(price_type_valid·amount_nonnegative·
       currency_uppercase)이 자동 반영됐다. 불변 테이블 아님 → MUTABLE_TABLES 등록.
  ☑ 멱등 UNIQUE는 unique_active() 부분 인덱스인가 (§17.4)
     → uq_sku_prices_sku_id_price_type_currency_effective_from_active (62자,
       PostgreSQL 상한 63자에 근접 — 컬럼을 더 넣으면 잘린다. constraints.py의
       _guard_name이 잘리기 전에 실패시킨다).
  ☑ downgrade()가 실제로 되돌리는가 → 인덱스·테이블 제거로 완전 복귀
  ☑ 되돌릴 수 없는 변경 없음

■ 종료일 컬럼이 없는 것이 설계다 (ADR-0017)

  다음 행의 발효일이 곧 이전 행의 종료다. 종료일을 두면 기간 겹침이 표현
  가능해지고, 겹친 이력은 "그때 단가"를 두 개로 만든다 — 이 테이블의 존재
  이유가 무너진다. **나중에 "편의상" 종료일을 추가하지 말 것.**

■ 금액은 BIGINT 정수 최소단위 (§2 ADR-02 / GC-G1)

  USD 12.34 → 1234. 통화별 자릿수의 유일한 출처는 app/core/money.py이고,
  DB에는 통화 목록 CHECK를 두지 않는다 — 그 목록이 money.py와 갈라지는 순간
  어느 쪽이 진실인지 알 수 없어진다. 0을 막지 않는 이유는 사은품 0원이
  실재하고 §20 B도 무상(금액 0)을 인정하기 때문이다.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "1e916401c142"
down_revision: str | None = "0f68d6635b0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku_prices",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("sku_id", sa.BigInteger(), nullable=False),
        sa.Column("price_type", sa.String(length=10), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "price_type IN ('PURCHASE', 'SALES')", name=op.f("ck_sku_prices_price_type_valid")
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_sku_prices_amount_nonnegative")),
        sa.CheckConstraint(
            "currency = upper(currency)", name=op.f("ck_sku_prices_currency_uppercase")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_sku_prices_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["skus.id"], name=op.f("fk_sku_prices_sku_id_skus"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_sku_prices_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sku_prices")),
    )
    op.create_index(
        "uq_sku_prices_sku_id_price_type_currency_effective_from_active",
        "sku_prices",
        ["sku_id", "price_type", "currency", "effective_from"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_sku_prices_sku_id_price_type_currency_effective_from_active",
        table_name="sku_prices",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("sku_prices")
    # ### end Alembic commands ###
