"""product hierarchy brands products and sku formulation link

리비전 ID: c2f216777de3
직전 리비전: 65f7c2c5b6fa
생성 시각(UTC): 2026-07-29 00:36:58.273186+00:00

S1-1 첫 마이그레이션 — §4.1의 제품(처방)↔SKU 분리와 §4.2의 세트 구분(ADR-0016).

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ☑ 컬럼 rename이 drop+add로 생성되지 않았는가 → 신규 테이블 2개 + 신규 컬럼 2개뿐
  ☑ CHECK 제약·부분 인덱스·server_default·트리거·GRANT는 자동 감지되지 않는다 — 손으로 썼는가
     → **skus의 CHECK 2건(kind_valid·kind_product_link)을 autogenerate가 감지하지 못해
       손으로 추가**했다(기존 테이블에 붙는 CHECK는 감지 대상이 아니다).
       products의 status CHECK와 두 부분 유니크는 신규 테이블이라 자동 반영됐다.
       불변 테이블 아님 → revoke_mutations() 대상 아님(MUTABLE_TABLES 등록).
  ☑ 멱등 UNIQUE는 unique_active() 부분 인덱스인가 (§17.4)
     → uq_brands_brand_code_active / uq_products_product_code_active
  ☑ downgrade()가 실제로 되돌리는가
     → CHECK·FK·컬럼·인덱스·테이블 역순 제거. 백필로 만든 brands·products 행은
       테이블째 사라진다(skus.product_id도 함께 사라지므로 고아 참조는 남지 않는다).
  ☑ 되돌릴 수 없는 변경 없음

■ 기존 SKU 백필 (ADR-0016 A2)

  `kind_product_link` CHECK가 "SINGLE이면 처방 필수"를 요구하므로, S0-2에서 이미
  등록된 SKU가 한 건이라도 있으면 CHECK를 거는 순간 실패한다. 그래서 CHECK보다
  **먼저** 처방을 만들어 연결한다.

  ★ 자동 생성한 brands·products 행에는 **생성 출처를 description에 남긴다**.
    출처 없는 자동 생성 행은 나중에 사람이 만든 마스터와 구분되지 않고, 구분되지
    않으면 아무도 정리하지 않는다.

  ★ soft delete된 SKU도 백필 대상이다 — CHECK는 deleted_at과 무관하게 전 행에
    적용된다. 그래서 제품 코드를 `P-<sku_code>`가 아니라 `P-<sku.id>`로 만든다:
    품번이 재유입된 경우(§17.4 "재유입은 부활이 아니라 신규") 같은 품번의 SKU가
    둘 이상 존재할 수 있고, 그러면 코드가 충돌해 마이그레이션이 실패한다.
    사람이 읽는 이름(name_ko)에는 원래 SKU 이름을 그대로 옮긴다.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "c2f216777de3"
down_revision: str | None = "65f7c2c5b6fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: 자동 생성 행에 남기는 출처. 사람이 만든 마스터와 구분되는 유일한 표식이다.
_BACKFILL_BRAND_NOTE = (
    "S1-1 마이그레이션(c2f216777de3)이 기존 SKU의 처방 백필을 위해 자동 생성했다. "
    "실제 브랜드로 교체할 것."
)
_BACKFILL_PRODUCT_NOTE_SQL = (
    "'S1-1 마이그레이션(c2f216777de3)이 SKU ' || s.sku_code || '에서 자동 생성했다. "
    "실제 처방으로 정리할 것.'"
)


def _backfill_products_for_existing_skus() -> None:
    """처방 없는 기존 SKU마다 제품을 만들어 연결한다 (전부 idempotent한 조건부 SQL)."""
    # ① 백필 대상이 있을 때만 임시 브랜드를 만든다. 새 DB에는 아무것도 안 생긴다.
    op.execute(
        sa.text(
            """
            INSERT INTO brands (brand_code, name_ko, description)
            SELECT 'UNCLASSIFIED', '미분류', :note
            WHERE EXISTS (SELECT 1 FROM skus WHERE product_id IS NULL)
            """
        ).bindparams(note=_BACKFILL_BRAND_NOTE)
    )
    # ② SKU 하나당 처방 하나.
    op.execute(
        f"""
        INSERT INTO products (brand_id, product_code, name_ko, description, status)
        SELECT b.id, 'P-' || s.id, s.name_ko, {_BACKFILL_PRODUCT_NOTE_SQL}, 'ACTIVE'
        FROM skus s
        CROSS JOIN brands b
        WHERE b.brand_code = 'UNCLASSIFIED' AND s.product_id IS NULL
        """
    )
    # ③ 연결.
    op.execute(
        """
        UPDATE skus s
        SET product_id = p.id
        FROM products p
        WHERE p.product_code = 'P-' || s.id AND s.product_id IS NULL
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("brand_code", sa.String(length=20), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_brands_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_brands_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
    )
    op.create_index(
        "uq_brands_brand_code_active",
        "brands",
        ["brand_code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("brand_id", sa.BigInteger(), nullable=False),
        sa.Column("product_code", sa.String(length=40), nullable=False),
        sa.Column("name_ko", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'DISCONTINUED')", name=op.f("ck_products_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_products_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_products_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(
        "uq_products_product_code_active",
        "products",
        ["product_code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.add_column(
        "skus", sa.Column("kind", sa.String(length=10), server_default="SINGLE", nullable=False)
    )
    op.add_column("skus", sa.Column("product_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_skus_product_id_products"),
        "skus",
        "products",
        ["product_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###

    # ↓ 손으로 추가한 부분 — autogenerate가 감지하지 못하는 것들.
    _backfill_products_for_existing_skus()

    op.create_check_constraint(op.f("ck_skus_kind_valid"), "skus", "kind IN ('SET', 'SINGLE')")
    # ★ 양방향이다. "SET이면 NULL"만 걸면 처방 없는 단품이 조용히 들어온다(ADR-0016).
    op.create_check_constraint(
        op.f("ck_skus_kind_product_link"),
        "skus",
        "(kind = 'SINGLE' AND product_id IS NOT NULL) OR (kind = 'SET' AND product_id IS NULL)",
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_skus_kind_product_link"), "skus", type_="check")
    op.drop_constraint(op.f("ck_skus_kind_valid"), "skus", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_skus_product_id_products"), "skus", type_="foreignkey")
    op.drop_column("skus", "product_id")
    op.drop_column("skus", "kind")
    op.drop_index(
        "uq_products_product_code_active",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("products")
    op.drop_index(
        "uq_brands_brand_code_active",
        table_name="brands",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("brands")
    # ### end Alembic commands ###
