"""ingredients product_ingredients ingredient_rules

리비전 ID: 60ca106f8bc7
직전 리비전: 306c631abb8f
생성 시각(UTC): 2026-07-30 02:04:25.550840+00:00

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ■ rename 없음 — 신규 테이블 3개뿐이다.
  ■ CHECK 11건 전부 create_table 안에 포함됐다(신규 테이블의 CHECK는 감지된다 —
    S1-1 함정 ①은 **기존 테이블에 붙는** CHECK만 해당). 모델과 1:1 대조 완료:
    ingredients 2 / ingredient_rules 6 / product_ingredients 3.
  ■ 멱등 UNIQUE 3건 전부 unique_active 부분 인덱스(WHERE deleted_at IS NULL).
    최장 이름 55자(uq_product_ingredients_…)로 63자 상한 여유.
  ■ downgrade가 인덱스·테이블 전부 되돌린다 — kbos_migr 왕복으로 확인.
  ■ GRANT/REVOKE 없음 — 셋 다 MUTABLE(마스터, table_policy 등록).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "60ca106f8bc7"
down_revision: str | None = "306c631abb8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("inci_name", sa.String(length=200), nullable=False),
        sa.Column("inci_name_normalized", sa.String(length=200), nullable=False),
        sa.Column("name_ko", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "inci_name_normalized = upper(inci_name_normalized)",
            name=op.f("ck_ingredients_inci_name_normalized_upper"),
        ),
        sa.CheckConstraint(
            "length(btrim(inci_name)) > 0", name=op.f("ck_ingredients_inci_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_ingredients_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_ingredients_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
    )
    op.create_index(
        "uq_ingredients_inci_name_normalized_active",
        "ingredients",
        ["inci_name_normalized"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "ingredient_rules",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("ingredient_id", sa.BigInteger(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("rule_type", sa.String(length=10), nullable=False),
        sa.Column("max_concentration_pct", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("last_verified_on", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "(rule_type = 'RESTRICTED' AND max_concentration_pct IS NOT NULL) OR (rule_type = 'PROHIBITED' AND max_concentration_pct IS NULL)",
            name=op.f("ck_ingredient_rules_rule_type_limit_link"),
        ),
        sa.CheckConstraint(
            "country_code ~ '^[A-Z]{2}$'", name=op.f("ck_ingredient_rules_country_code_format")
        ),
        sa.CheckConstraint(
            "rule_type IN ('PROHIBITED', 'RESTRICTED')",
            name=op.f("ck_ingredient_rules_rule_type_valid"),
        ),
        sa.CheckConstraint(
            "length(btrim(source_url)) > 0", name=op.f("ck_ingredient_rules_source_url_not_blank")
        ),
        sa.CheckConstraint(
            "max_concentration_pct <= 100",
            name=op.f("ck_ingredient_rules_max_concentration_pct_max"),
        ),
        sa.CheckConstraint(
            "max_concentration_pct > 0",
            name=op.f("ck_ingredient_rules_max_concentration_pct_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_ingredient_rules_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_ingredient_rules_ingredient_id_ingredients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_ingredient_rules_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredient_rules")),
    )
    op.create_index(
        "uq_ingredient_rules_ingredient_id_country_code_active",
        "ingredient_rules",
        ["ingredient_id", "country_code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "product_ingredients",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("ingredient_id", sa.BigInteger(), nullable=False),
        sa.Column("concentration_pct", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "concentration_pct <= 100", name=op.f("ck_product_ingredients_concentration_pct_max")
        ),
        sa.CheckConstraint(
            "concentration_pct > 0", name=op.f("ck_product_ingredients_concentration_pct_positive")
        ),
        sa.CheckConstraint(
            "display_order > 0", name=op.f("ck_product_ingredients_display_order_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_product_ingredients_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_product_ingredients_ingredient_id_ingredients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_ingredients_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_product_ingredients_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_ingredients")),
    )
    op.create_index(
        "uq_product_ingredients_product_id_ingredient_id_active",
        "product_ingredients",
        ["product_id", "ingredient_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_product_ingredients_product_id_ingredient_id_active",
        table_name="product_ingredients",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("product_ingredients")
    op.drop_index(
        "uq_ingredient_rules_ingredient_id_country_code_active",
        table_name="ingredient_rules",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("ingredient_rules")
    op.drop_index(
        "uq_ingredients_inci_name_normalized_active",
        table_name="ingredients",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("ingredients")
    # ### end Alembic commands ###
