"""sku hs codes with evidence and hs version

리비전 ID: 22531fb72e82
직전 리비전: 7c4162d3ceb1
생성 시각(UTC): 2026-07-29 01:57:00.843981+00:00

S1-1 세 번째 마이그레이션 — §4.1의 국가별 HS 세번(세율 메모+근거링크), ADR-0019.

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ☑ 컬럼 rename이 drop+add로 생성되지 않았는가 → 신규 테이블뿐
  ☑ CHECK 제약·부분 인덱스·server_default·트리거·GRANT는 자동 감지되지 않는다 — 손으로 썼는가
     → **이번엔 전부 자동 반영됐다.** 신규 테이블의 CHECK는 create_table에
       포함되기 때문이다(커밋 2·3에서 미감지였던 것은 **기존 테이블에 붙는**
       CHECK였다 — 이 차이가 함정의 정확한 경계다). 확인한 4건:
       country_code_format / hs_version_format / hs_code_digits / source_url_not_blank.
       불변 테이블 아님 → revoke_mutations() 대상 아님(MUTABLE_TABLES 등록).
  ☑ 멱등 UNIQUE는 unique_active() 부분 인덱스인가 (§17.4)
     → uq_sku_hs_codes_sku_id_country_code_hs_version_active.
       **hs_version이 키에 있다** — 빼면 HS 개정 때 기존 행을 덮어써야 하고,
       덮어쓰는 순간 GC-B3("과거 판정은 당시 버전으로")가 마스터 쪽에서 무너진다.
  ☑ downgrade()가 실제로 되돌리는가 → 인덱스·테이블 제거로 완전 복귀
  ☑ 되돌릴 수 없는 변경 없음

■ 근거링크·최종확인일이 NOT NULL인 이유 (ADR-03)

  "모든 요건·세율·기한 데이터에 근거링크+최종확인일 필수"가 ADR-03이다.
  nullable로 두고 화면 경고로 대신하면 그 경고는 반드시 무시되고, 근거 없는
  세번이 통관 서류로 흘러간다. **세율은 숫자가 아니라 메모(Text)다** — 숫자
  컬럼이면 곧 곱하기 시작하고, 그 순간 §1이 비범위로 못박은 "자동 판정"이 된다.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "22531fb72e82"
down_revision: str | None = "7c4162d3ceb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku_hs_codes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("sku_id", sa.BigInteger(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("hs_version", sa.String(length=10), nullable=False),
        sa.Column("hs_code", sa.String(length=12), nullable=False),
        sa.Column("tariff_note", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("last_verified_on", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "country_code ~ '^[A-Z]{2}$'", name=op.f("ck_sku_hs_codes_country_code_format")
        ),
        sa.CheckConstraint(
            "hs_code ~ '^[0-9]{6,12}$'", name=op.f("ck_sku_hs_codes_hs_code_digits")
        ),
        sa.CheckConstraint(
            "hs_version ~ '^HS[0-9]{4}$'", name=op.f("ck_sku_hs_codes_hs_version_format")
        ),
        sa.CheckConstraint(
            "length(btrim(source_url)) > 0", name=op.f("ck_sku_hs_codes_source_url_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_sku_hs_codes_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["skus.id"], name=op.f("fk_sku_hs_codes_sku_id_skus"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_sku_hs_codes_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sku_hs_codes")),
    )
    op.create_index(
        "uq_sku_hs_codes_sku_id_country_code_hs_version_active",
        "sku_hs_codes",
        ["sku_id", "country_code", "hs_version"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_sku_hs_codes_sku_id_country_code_hs_version_active",
        table_name="sku_hs_codes",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("sku_hs_codes")
    # ### end Alembic commands ###
