"""common tables: numbering idempotency outbox worklist platform

리비전 ID: 238dad88bdf5
직전 리비전: 0503591a1409
생성 시각(UTC): 2026-07-27 08:57:13.943077+00:00

S0-2 두 번째 마이그레이션 — WBS S0-2 산출물의 공통 테이블 11종.
관련: DESIGN.md §3 [공통] / §15 / §17.1·17.3·17.4 / ADR-07·10·11 / ADR-0012·0014.

  doc_number_seq      채번 카운터 (§17.3 MAX+1 금지)
  idempotency_keys    쓰기 API 멱등 (§17.4 / ADR-0014)
  events              아웃박스 (§17.1 — 디스패처는 S2-3)
  tasks               담당자 컬럼 포함 (ADR-0012 구조분)
  alert_rules/alerts  수신 대상 컬럼 포함 (ADR-0012 구조분 / ADR-07 dedup·ack)
  scheduled_jobs      배치 레지스트리 (§15 — 실행기는 S2-3)
  feature_flags / external_refs / custom_field_defs / custom_field_values

체크리스트 (autogenerate 결과는 초안이다 — 사람이 전건 확인한다):
  ☑ 컬럼 rename이 drop+add로 생성되지 않았는가 → 신규 테이블뿐, rename 없음
  ☑ CHECK 제약·부분 인덱스·server_default·트리거·GRANT는 자동 감지되지 않는다 — 손으로 썼는가
     → CHECK·부분 인덱스는 모델 __table_args__에서 나와 아래 SQL에 반영됨.
       불변 테이블 없음 → revoke_mutations() 호출 대상 없음(전부 MUTABLE_TABLES).
  ☑ 멱등 UNIQUE는 unique_active() 부분 인덱스인가 (§17.4)
     → alert_rules.code / alerts.dedup_key / scheduled_jobs.code / feature_flags.code /
       external_refs(시스템·엔터티·외부코드) / custom_field_defs / custom_field_values.
       doc_number_seq·idempotency_keys는 soft delete가 없어 전 UNIQUE가 맞다
       (사유는 각 모델 독스트링).
  ☑ downgrade()가 실제로 되돌리는가 → 시드 없음, drop_table로 완전 복귀
  ☑ 되돌릴 수 없는 변경 없음

시드를 넣지 않는다. scheduled_jobs에 실행기(S2-3)가 없는 상태로 배치 행만 넣으면
"등록됐는데 아무도 안 도는" 상태가 되고, 그 행은 관리 화면에서 정상으로 보인다.
멱등 키 TTL 청소는 그때까지 키 발급 경로가 겸한다(ADR-0014).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "238dad88bdf5"
down_revision: str | None = "0503591a1409"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doc_number_seq",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("prefix", sa.String(length=20), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_number", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_number >= 0", name=op.f("ck_doc_number_seq_last_number_nonnegative")
        ),
        sa.CheckConstraint(
            "year BETWEEN 2000 AND 2999", name=op.f("ck_doc_number_seq_year_plausible")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doc_number_seq")),
        sa.UniqueConstraint("prefix", "year", name="uq_doc_number_seq_prefix_year"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("aggregate_type", sa.String(length=60), nullable=True),
        sa.Column("aggregate_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(
        "ix_events_aggregate", "events", ["aggregate_type", "aggregate_id"], unique=False
    )
    op.create_index(
        "ix_events_pending",
        "events",
        ["id"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=10), server_default="INFO", nullable=False),
        sa.Column("recipient_user_id", sa.BigInteger(), nullable=True),
        sa.Column("recipient_role", sa.String(length=20), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "recipient_role IN ('ADMIN', 'CERT', 'LOGISTICS', 'TRADE', 'VIEWER')",
            name=op.f("ck_alert_rules_recipient_role_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('CRITICAL', 'INFO', 'WARN')", name=op.f("ck_alert_rules_severity_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_alert_rules_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_alert_rules_recipient_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_alert_rules_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
    )
    op.create_index("ix_alert_rules_event_type", "alert_rules", ["event_type"], unique=False)
    op.create_index(
        "uq_alert_rules_code_active",
        "alert_rules",
        ["code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "custom_field_defs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("label_ko", sa.String(length=60), nullable=False),
        sa.Column("data_type", sa.String(length=20), nullable=False),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_required", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "data_type IN ('BOOLEAN', 'DATE', 'NUMBER', 'SELECT', 'TEXT')",
            name=op.f("ck_custom_field_defs_data_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_custom_field_defs_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_custom_field_defs_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_field_defs")),
    )
    op.create_index(
        "uq_custom_field_defs_entity_type_code_active",
        "custom_field_defs",
        ["entity_type", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "external_refs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("system", sa.String(length=30), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("external_code", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_external_refs_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_external_refs_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_refs")),
    )
    op.create_index(
        "ix_external_refs_entity", "external_refs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        "uq_external_refs_system_entity_type_external_code_active",
        "external_refs",
        ["system", "entity_type", "external_code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_feature_flags_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_feature_flags_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
    )
    op.create_index(
        "uq_feature_flags_code_active",
        "feature_flags",
        ["code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=False),
        sa.Column("endpoint", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_idempotency_keys_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint(
            "actor_user_id",
            "endpoint",
            "idempotency_key",
            name="uq_idempotency_keys_actor_endpoint_key",
        ),
    )
    op.create_index(
        "ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("schedule", sa.String(length=60), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=10), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "last_status IN ('FAILED', 'OK', 'RUNNING')",
            name=op.f("ck_scheduled_jobs_last_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_scheduled_jobs_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_scheduled_jobs_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_jobs")),
    )
    op.create_index(
        "uq_scheduled_jobs_code_active",
        "scheduled_jobs",
        ["code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="OPEN", nullable=False),
        sa.Column("assignee_id", sa.BigInteger(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("entity_type", sa.String(length=60), nullable=True),
        sa.Column("entity_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "status IN ('CANCELLED', 'DONE', 'IN_PROGRESS', 'OPEN')",
            name=op.f("ck_tasks_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_tasks_assignee_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_tasks_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_tasks_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index("ix_tasks_assignee_id", "tasks", ["assignee_id"], unique=False)
    op.create_index("ix_tasks_entity", "tasks", ["entity_type", "entity_id"], unique=False)
    op.create_index("ix_tasks_status_due_date", "tasks", ["status", "due_date"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("alert_rule_id", sa.BigInteger(), nullable=True),
        sa.Column("recipient_user_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=10), server_default="INFO", nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entity_type", sa.String(length=60), nullable=True),
        sa.Column("entity_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "severity IN ('CRITICAL', 'INFO', 'WARN')", name=op.f("ck_alerts_severity_valid")
        ),
        sa.ForeignKeyConstraint(
            ["alert_rule_id"],
            ["alert_rules.id"],
            name=op.f("fk_alerts_alert_rule_id_alert_rules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_alerts_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_alerts_recipient_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_alerts_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index("ix_alerts_entity", "alerts", ["entity_type", "entity_id"], unique=False)
    op.create_index("ix_alerts_recipient_user_id", "alerts", ["recipient_user_id"], unique=False)
    op.create_index(
        "uq_alerts_dedup_key_active",
        "alerts",
        ["dedup_key"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "custom_field_values",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("definition_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_custom_field_values_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["custom_field_defs.id"],
            name=op.f("fk_custom_field_values_definition_id_custom_field_defs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_custom_field_values_updated_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_field_values")),
    )
    op.create_index(
        "uq_custom_field_values_definition_id_entity_id_active",
        "custom_field_values",
        ["definition_id", "entity_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_custom_field_values_definition_id_entity_id_active",
        table_name="custom_field_values",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("custom_field_values")
    op.drop_index(
        "uq_alerts_dedup_key_active",
        table_name="alerts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_alerts_recipient_user_id", table_name="alerts")
    op.drop_index("ix_alerts_entity", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_tasks_status_due_date", table_name="tasks")
    op.drop_index("ix_tasks_entity", table_name="tasks")
    op.drop_index("ix_tasks_assignee_id", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(
        "uq_scheduled_jobs_code_active",
        table_name="scheduled_jobs",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("scheduled_jobs")
    op.drop_index("ix_idempotency_keys_expires_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index(
        "uq_feature_flags_code_active",
        table_name="feature_flags",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("feature_flags")
    op.drop_index(
        "uq_external_refs_system_entity_type_external_code_active",
        table_name="external_refs",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_external_refs_entity", table_name="external_refs")
    op.drop_table("external_refs")
    op.drop_index(
        "uq_custom_field_defs_entity_type_code_active",
        table_name="custom_field_defs",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("custom_field_defs")
    op.drop_index(
        "uq_alert_rules_code_active",
        table_name="alert_rules",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_alert_rules_event_type", table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index(
        "ix_events_pending", table_name="events", postgresql_where=sa.text("published_at IS NULL")
    )
    op.drop_index("ix_events_aggregate", table_name="events")
    op.drop_table("events")
    op.drop_table("doc_number_seq")
    # ### end Alembic commands ###
